repos:
  GitHub: [
    'MicrosoftDocs/azure-docs'
  ]
folders:
  'MicrosoftDocs/azure-docs': [
    'articles/ai-services',
    'articles/application-gateway',
    'articles/app-service'
  ]
