repos:
  GitHub: [jochenvw/kv-and-java-signing, 
           jochenvw/azure-durable-functions-examples, 
           jochenvw/JavaApp,
           jochenvw/sec-bot]
assessments: [
  {
    name: 'security',
    explain-prompt: 'prompts/02_sec_assess.md',
    code-prompt: 'prompts/02_sec_code.md',
  }
]
