repos:
  GitHub: [jochenvw/kv-and-java-signing, 
           jochenvw/azure-durable-functions-examples, 
           jochenvw/JavaApp,
           jochenvw/sec-bot]
assessments: [
  {
    name: 'security',
    explain-prompt: '_prompts/02_sec_md.md',
    code-prompt: '_prompts/02_sec_code.md',
  },
  {
    name: 'finops',
    explain-prompt: '_prompts/03_finops_md.md',
    code-prompt: '_prompts/02_sec_code.md',
  }
]
